### PR TITLE
refactored _parse_selfies

### PR DESCRIPTION
**Pull request by masrul**
The _parse_selfies  function  in decoder.py does not catch some syntax error, 

Simple selfies: [A][B][C] 

**case1:  missing "[" at begining**

    selfies = "A][B][C]" 
    the function does not raise error, rather parses, [B], [C] 

**case:2** missing "]" 

    selfies = "[A[B][C]"  
    the function does not raise error, rather parses, [A[B], [C] 

**case-3**: misisng both "[]" at begining 

    selfies=A[B][C]
    the function does not raise error, rather parses, [B], [C] 

**case-4**: extra "[" 
    
    selfies=[A][[[B][C] 
    the function does not raise error, rather parse, [A], [[[B], [C] 

**case-5**: inconsistent spacing rules between symbols 
    
    o Spacing at begining  is parsed  without  error e.g. "   [A][B][C]" 
    o Spacing at the end and middle raises error, e.g., "[A] [B][C]" and "[A][B][C]  "

So, I am proposing a refactoring of the _parse_selfies function. Typically, braket matching can be better handled using a stack. When "[" is encountered, appended into the stack, and "]" is encountered just poped and matched if it is matching brace ("["). The refactored function is also consistent with spacing, it does not allow any spacing between symbols. Though spacing rules can be relaxed, if required.

### CODE REVIEW

**Comment by masrul** [comment]
As we have only square braket, stack is not needed. So, I replaced it with a logical variable. Which should significantly improves speed of parsing.

**Comment by MarioKrenn6240** [comment]
Thank you. Would it be possible that you benchmark your code with the code by @clavigne in #59 ? I would like to use the faster option finally.

**Comment by masrul** [comment]
I did a benchmark using following code, function names defined according to PR number

```python 
from typing import Dict, Iterable, List, Optional, Tuple, Union
import time


def _parse_selfies_pr57(selfies: str) -> Iterable[str]:

    syntax_err = "malformed SELIFES, misplaced or missing brackets"
    save = False

    for char in selfies:

        if char not in "[]" and save:
            symbol += char

        elif char == "[" and not save:
            symbol = ""
            save = True

        elif char == "]" and save:
            save = False
            if symbol != "nop":  # skip [nop]
                yield "[" + symbol + "]"
        else:
            raise ValueError(syntax_err)

    if save:
        raise ValueError(syntax_err)

    while True:  # no more symbols left
        yield ""


def _parse_selfies_pr59(selfies: str) -> Iterable[str]:

    left_idx = selfies.find("[")
    if "]" in selfies[:left_idx]:
        raise ValueError("malformed SELFIES, " "misplaced or missing brackets")

    while 0 <= left_idx < len(selfies):
        right_idx = selfies.find("]", left_idx + 1)

        if (selfies[left_idx] != "[") or (right_idx == -1):
            raise ValueError("malformed SELFIES, " "misplaced or missing brackets")

        next_symbol = selfies[left_idx : right_idx + 1]
        if "[" in next_symbol[1:]:
            raise ValueError("malformed SELFIES, " "misplaced or missing brackets")
        left_idx = right_idx + 1

        if next_symbol != "[nop]":  # skip [nop]
            yield next_symbol

    while True:  # no more symbols left
        yield ""


# very long selfies for benchmaring
selfies = "[C][Branch1_2][Branch1_1][Branch1_1][C][C][Cl][F]" * 10
nruns = 20000  # repeating function call for 10000 times

start_time = time.time()
for _ in range(nruns):
    for symbol in _parse_selfies_pr57(selfies):
        if symbol == "":
            break
end_time = time.time()
print("Issue-57", end_time - start_time)

start_time = time.time()
for _ in range(nruns):
    for symbol in _parse_selfies_pr59(selfies):
        if symbol == "":
            break
end_time = time.time()
print("Issue-59", end_time - start_time)

```

**I tested it in my computer. Both PR seems to produce identical performances.  In some runs, I found #57  is marginally faster (which is not mentionable).**

I think #59  can not catch the following errors "A[B][C]" (missing brackets at the beginning) and white space at the beginning.

**Comment by MarioKrenn6240** [comment]
@masrul a quick question, do you plan to continue on this PR, or can we close it?

**Comment by masrul** [comment]
@MarioKrenn6240  Sorry for, delay.  I have raised a new PR #77 to address #57. Due to significant changes in newer selfies, I raised new PR. 

Thanks 
Masrul

**Comment by masrul** [comment]
Addressed with PR #77.

**Pull request closed without merging**
