### PR TITLE
Added cache for get_semantic_robust_alphabet

### PR DESCRIPTION
**Pull request by whitead**
`get_semantic_robust_alphabet` is called frequently in STONED SELFIES code (e.g., in [tutorial](https://github.com/aspuru-guzik-group/stoned-selfies/blob/main/stoned_selfies_tut.ipynb)) and is a relatively expensive function. Since the output doesn't change, I added a cache which should greatly speed-up STONED SELFIES code that calls this in each loop.

### CODE REVIEW

**Comment by MarioKrenn6240** [comment]
Thanks a lot for this PR, makes a lot of sense. In a quick internal discussion, we identified one potential issue that you might be able to fix easily. The bond-constrained can be modified using `set_semantic_constraints` (see [examples](https://github.com/aspuru-guzik-group/selfies/blob/master/examples/selfies_examples.ipynb)):

```
import selfies as sf


print(sf.get_semantic_robust_alphabet())

default_constraints = sf.get_semantic_constraints()
new_constraints = default_constraints
new_constraints['XX']=4
sf.set_semantic_constraints(new_constraints)

print(sf.get_semantic_robust_alphabet())
```
Here, the second output is supposed to be different. Using your PR, the output of `get_semantic_robust_alphabet()` wouldn't change, right? Simple fix could be to reset the cache at call of `set_semantic_constraints`.

**Comment by whitead** [comment]
Nice catch. Added unit test and cache clear

**Comment by whitead** [comment]
Ok, think I got the unit tests fixed.

**Comment by MarioKrenn6240** [comment]
Great, thanks for this! Will be part of official SELFIES 1.0.5 version (we want to get one bugfix out before publishing it, hope less than a week).

Welcome to the team :)

**Pull request merged**
